declare const process: { env: Record<string, string | undefined>; exitCode?: number };
export {};
const WORKER_URL=(process.env.WORKER_URL||"https://arqon-contextos-broker.sonarum.workers.dev").replace(/\/+$/,"");
const spec=process.env.PM_PLAN_SPECIFICATION_ID; if(!spec) throw new Error("PM_PLAN_SPECIFICATION_ID is required; create it with the PM specify live flow first.");
const token=process.env.BROKER_KEY_PM; if(!token) throw new Error("BROKER_KEY_PM is required");
async function post(body:unknown){const r=await fetch(`${WORKER_URL}/v1/pm/plan`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify(body)}); const t=await r.text(); let b:any=null; try{b=t?JSON.parse(t):null}catch{b=t} return {status:r.status,body:b};}
function assert(c:boolean,m:string){if(!c) throw new Error(m)}
async function main(){const suffix=String(Date.now()).slice(-10); const payload={specification_id:spec,idempotency_key:`plan-live-${suffix}`,plan_title:"PM Plan Live Smoke",plan_body:"Plan phases and gates. Do not create tasks."}; const ok=await post(payload); assert(ok.status===201,`plan create failed ${JSON.stringify(ok)}`); assert(ok.body.plan.output_artifacts.plan.artifact_type==="plan","plan artifact"); const replay=await post(payload); assert(replay.status===200 && replay.body.idempotent_replay===true,"replay failed"); const conflict=await post({...payload,plan_body:"Changed body"}); assert(conflict.status===409 && conflict.body.error.code==="PM_PLAN_IDEMPOTENCY_CONFLICT","conflict failed"); const bad=await post({specification_id:spec,idempotency_key:`plan-bad-${suffix}`,plan_title:"Bad",plan_body:"This is approved for release."}); assert(bad.status===409 && bad.body.error.code==="PM_PLAN_FORBIDDEN_CLAIM_INCLUDED","promotion guard failed"); console.log(JSON.stringify({ok:true,result:"PASS",worker_url:WORKER_URL,plan_id:ok.body.plan.plan_id},null,2));}
main().catch(e=>{console.error(e);process.exitCode=1});
