declare const process: { exitCode?: number };
import { handleWorkerFetch } from "../src/index.js";
import type { Env, ProjectConfig } from "../src/types.js";
import type { RepoStore, RepoFileRef, RepoWriteResult } from "../src/repo_store.js";

const labels=["REQUIRES_HUMAN_REVIEW","development diagnostic only","NOT SEALED-TEST CERTIFIED","not promotable"];
const env:Env={BROKER_VERSION:"test",DEFAULT_BRANCH:"main",GITHUB_APP_ID:"x",GITHUB_APP_INSTALLATION_ID:"x",GITHUB_APP_PRIVATE_KEY:"x",BROKER_KEY_PM:"pm-token",BROKER_KEY_CODER:"coder-token",BROKER_KEY_AUDITOR:"auditor-token",BROKER_KEY_HELPER:"helper-token",BROKER_KEY_EXPLORER:"explorer-token",BROKER_KEY_HYPOTHESIZER:"hypothesizer-token",BROKER_KEY_DESIGNER:"designer-token",BROKER_KEY_SCIENCE_AUDITOR:"science-auditor-token",BROKER_KEY_SCIENCE_EXECUTOR:"science-executor-token",BROKER_KEY_HUMAN:"human-token"};
const files=new Map<string,string>(); let n=0;
const store:RepoStore={
 async fetchFile(_e:Env,_p:ProjectConfig,path:string):Promise<RepoFileRef>{const c=files.get(path); if(c===undefined) throw new Error(`GitHub file fetch failed for ${path}: 404 offline missing`); return {path,sha:`sha-${path}`,content:c};},
 async writeFile(_e:Env,_p:ProjectConfig,path:string,content:string,_m:string):Promise<RepoWriteResult>{files.set(path,content); n++; return {path,sha:`sha-write-${n}`};}
};
function assert(x:boolean,m:string){if(!x) throw new Error(m);}
function auth(role:"PM"|"CODER"|"HELPER"){return `Bearer ${role==="PM"?env.BROKER_KEY_PM:role==="CODER"?env.BROKER_KEY_CODER:env.BROKER_KEY_HELPER}`;}
async function post(path:string,role:"PM"|"CODER"|"HELPER",body:any){const r=await handleWorkerFetch(new Request(`https://offline.local${path}`,{method:"POST",headers:{authorization:auth(role),"content-type":"application/json"},body:JSON.stringify(body)}),env,{flowRepoStore:store}); const t=await r.text(); let b:any=null; try{b=t?JSON.parse(t):null}catch{b=t}; return {status:r.status,body:b};}
function seed(){const flowId="FLOW-2026-8888", id="TASKS-001", rec="governance/context/coder_tasks/TASKS-001.json"; const art={artifact_id:"ART-TASKS-001",artifact_type:"coder_tasks",title:"Coder tasks",role:"CODER_AI",created_at:"2026-01-01T00:00:00.000Z",source_path:"governance/flows/FLOW-2026-8888/artifacts/ART-TASKS-001.md",source_sha:"sha-tasks"};
files.set("governance/context/generated_coder_tasks_context.json",JSON.stringify({schema_version:"coder_tasks_context_index.v0.1",project:"ArqonZero",updated_at:"2026-01-01T00:00:00.000Z",entries:[{coder_tasks_id:id,coder_work_plan_id:"WP",tasking_id:"TASKING",plan_id:"PLAN",specification_id:"SPEC",intake_id:"INTAKE",handoff_id:"HANDOFF",code_flow_id:flowId,share_id:"SHARE",science_flow_id:"FLOW-2026-7777",share_packet_hash:"sharehash",evidence_level:"SUPPORTED_DIAGNOSTIC",uncertainty:"diagnostic only",coder_tasks_record_path:rec,created_at:"2026-01-01T00:00:00.000Z"}]}));
files.set(rec,JSON.stringify({schema_version:"coder_tasks_context.v0.1",official_artifact:true,project:"ArqonZero",coder_tasks_id:id,idempotency_key:"k",created_at:"2026-01-01T00:00:00.000Z",created_by_role:"CODER_AI",source_coder_work_plan:{coder_work_plan_id:"WP",coder_work_plan_record_path:"governance/context/coder_work_plan/WP.json",tasking_id:"TASKING",code_flow_id:flowId,plan_id:"PLAN",specification_id:"SPEC",intake_id:"INTAKE",handoff_id:"HANDOFF",share_id:"SHARE",science_flow_id:"FLOW-2026-7777",share_packet_hash:"sharehash",submitted_share_payload_hash:"submitted",handoff_payload_hash:"handoff",intake_payload_hash:"intake",specification_payload_hash:"spec",plan_payload_hash:"plan",tasking_payload_hash:"tasking",coder_work_plan_payload_hash:"wp",evidence_level:"SUPPORTED_DIAGNOSTIC",uncertainty:"diagnostic only",source_artifacts:["SRC"],resolved_source_artifacts:[{artifact_id:"SRC",artifact_type:"audit_report",title:"Audit",role:"SCIENCE_AUDITOR_AI",created_at:"2026-01-01T00:00:00.000Z",source_path:"source.md",source_sha:"sha"}],allowed_claims:["diagnostic"],forbidden_claims:["no certification"]},output_artifacts:{coder_tasks:art},submitted_payload_hash:"taskspayload",coder_tasks_record_path:rec,generated_coder_tasks_context_path:"governance/context/generated_coder_tasks_context.json",required_status_labels:labels}));
files.set(`governance/flows/${flowId}/flow_manifest.json`,JSON.stringify({schema_version:"flow_manifest.v0.3",official_artifact:true,project:"ArqonZero",flow_id:flowId,name:"code-flow",type:"code_flow",title:"Code",summary:"",status:"active",current_gate:"DRAFT",created_at:"2026-01-01T00:00:00.000Z",created_by_role:"PM_AI",updated_at:"2026-01-01T00:00:00.000Z",updated_by_role:"PM_AI",required_status_labels:labels,artifacts:[art],history:[]}));
files.set("governance/flows/flow_index.json",JSON.stringify({schema_version:"flow_index.v0.3",project:"ArqonZero",updated_at:"2026-01-01T00:00:00.000Z",flows:[{flow_id:flowId,name:"code-flow",type:"code_flow",title:"Code",status:"active",current_gate:"DRAFT",created_at:"2026-01-01T00:00:00.000Z",updated_at:"2026-01-01T00:00:00.000Z",source_path:`governance/flows/${flowId}/flow_manifest.json`}]})); return {flowId,id,rec};}
async function main(){const {flowId,id,rec}=seed();
const raw=await post(`/v1/flows/${flowId}/artifacts`,"CODER",{artifact_type:"implementation_bundle",title:"Raw bypass",body:"approved for release"}); assert(raw.status===403 && raw.body.error.code==="FLOW_ARTIFACT_ROUTE_REQUIRED","raw CODER implementation_bundle must be blocked");
const ok=await post("/v1/coder/implementation-bundle","CODER",{coder_tasks_id:id,idempotency_key:"impl-ok-0001",bundle_title:"OK",bundle_body:"Implementation proposal only. Do not authorize execution."}); assert(ok.status===201,`route should pass ${JSON.stringify(ok.body)}`);
const mm=await post("/v1/coder/implementation-bundle","CODER",{coder_tasks_id:id,coder_tasks_record_path:"governance/context/coder_tasks/WRONG.json",idempotency_key:"impl-mismatch-0001",bundle_title:"Mismatch",bundle_body:"proposal"}); console.error("mismatch_response", JSON.stringify(mm)); assert(mm.status===409 && mm.body.error.code==="CODER_IMPLEMENTATION_BUNDLE_TASKS_CONTEXT_MISMATCH","mismatch must fail");
const j=JSON.parse(files.get(rec)||"{}"); j.output_artifacts.coder_tasks.source_sha="wrong"; files.set(rec,JSON.stringify(j));
const sha=await post("/v1/coder/implementation-bundle","CODER",{coder_tasks_id:id,idempotency_key:"impl-sha-0001",bundle_title:"SHA",bundle_body:"proposal"}); assert(sha.status===409 && sha.body.error.code==="CODER_IMPLEMENTATION_BUNDLE_TASKS_ARTIFACT_SHA_MISMATCH","sha mismatch must fail");
j.output_artifacts.coder_tasks.source_sha="sha-tasks"; files.set(rec,JSON.stringify(j)); files.set("governance/context/coder_implementation_bundle/TASKS-001-impl-bad-0001.json",JSON.stringify({schema_version:"bad"}));
const bad=await post("/v1/coder/implementation-bundle","CODER",{coder_tasks_id:id,idempotency_key:"impl-bad-0001",bundle_title:"Bad",bundle_body:"proposal"}); assert(bad.status===409 && bad.body.error.code==="CODER_IMPLEMENTATION_BUNDLE_EXISTING_RECORD_INVALID","malformed record must fail");
console.log(JSON.stringify({ok:true,raw_status:raw.status,route_status:ok.status,mismatch_status:mm.status,sha_status:sha.status,bad_record_status:bad.status},null,2));}
main().catch(e=>{console.error(e);process.exitCode=1;});
