declare const process: { exitCode?: number };
import { handleWorkerFetch } from "../src/index.js";
import type { Env, ProjectConfig } from "../src/types.js";
import type { RepoStore, RepoFileRef, RepoWriteResult } from "../src/repo_store.js";
const labels = ["REQUIRES_HUMAN_REVIEW", "development diagnostic only", "NOT SEALED-TEST CERTIFIED", "not promotable"];
const env: Env = { BROKER_VERSION:"test", DEFAULT_BRANCH:"main", GITHUB_APP_ID:"x", GITHUB_APP_INSTALLATION_ID:"x", GITHUB_APP_PRIVATE_KEY:"x", BROKER_KEY_PM:"pm-token", BROKER_KEY_CODER:"coder-token", BROKER_KEY_AUDITOR:"auditor-token", BROKER_KEY_HELPER:"helper-token", BROKER_KEY_EXPLORER:"explorer-token", BROKER_KEY_HYPOTHESIZER:"hypothesizer-token", BROKER_KEY_DESIGNER:"designer-token", BROKER_KEY_SCIENCE_AUDITOR:"science-auditor-token", BROKER_KEY_SCIENCE_EXECUTOR:"science-executor-token", BROKER_KEY_HUMAN:"human-token" };
const files = new Map<string,string>(); const writes:string[]=[]; let wc=0;
const store: RepoStore = { async fetchFile(_e:Env,_p:ProjectConfig,path:string):Promise<RepoFileRef>{ const c=files.get(path); if(c===undefined) throw new Error(`GitHub file fetch failed for ${path}: 404 offline missing`); return {path,sha:`sha-${path}`,content:c}; }, async writeFile(_e:Env,_p:ProjectConfig,path:string,content:string,_m:string):Promise<RepoWriteResult>{ files.set(path,content); writes.push(path); wc++; return {path,sha:`sha-write-${wc}`}; } };
function assert(x:boolean,m:string){ if(!x) throw new Error(m); }
function tok(role:"PM"|"CODER"|"HELPER"|"AUDITOR"){ return role==="PM"?env.BROKER_KEY_PM:role==="CODER"?env.BROKER_KEY_CODER:role==="HELPER"?env.BROKER_KEY_HELPER:env.BROKER_KEY_AUDITOR; }
async function post(path:string, role:"PM"|"CODER"|"HELPER"|"AUDITOR"|"NONE", body:any){ const h=new Headers({"content-type":"application/json"}); if(role!=="NONE") h.set("authorization",`Bearer ${tok(role)}`); const r=await handleWorkerFetch(new Request(`https://offline.local${path}`,{method:"POST",headers:h,body:JSON.stringify(body)}),env,{flowRepoStore:store}); const t=await r.text(); let b:any=null; try{b=t?JSON.parse(t):null}catch{b=t}; return {status:r.status,body:b}; }
function seed(){ const flowId="FLOW-2026-4242", implId="IMPL-001", rec="governance/context/coder_implementation_bundle/IMPL-001.json"; const art={artifact_id:"ART-IMPL-001",artifact_type:"implementation_bundle",title:"Implementation Bundle",role:"CODER_AI",created_at:"2026-01-01T00:00:00.000Z",source_path:"governance/flows/FLOW-2026-4242/artifacts/ART-IMPL-001.md",source_sha:"sha-impl"};
files.set("governance/context/generated_coder_implementation_bundle_context.json",JSON.stringify({schema_version:"coder_implementation_bundle_context_index.v0.1",project:"ArqonZero",updated_at:"2026-01-01T00:00:00.000Z",entries:[{implementation_bundle_id:implId,coder_tasks_id:"TASKS-001",coder_work_plan_id:"WORKPLAN-001",tasking_id:"TASKING-001",plan_id:"PLAN-001",specification_id:"SPEC-001",intake_id:"INTAKE-001",handoff_id:"PM-HANDOFF-001",code_flow_id:flowId,share_id:"SHARE-001",science_flow_id:"SCIENCE-001",share_packet_hash:"sharehash",evidence_level:"SUPPORTED_DIAGNOSTIC",uncertainty:"diagnostic only",implementation_bundle_record_path:rec,created_at:"2026-01-01T00:00:00.000Z"}]}));
files.set(rec,JSON.stringify({schema_version:"coder_implementation_bundle_context.v0.1",official_artifact:true,project:"ArqonZero",implementation_bundle_id:implId,idempotency_key:"impl-key-0001",created_at:"2026-01-01T00:00:00.000Z",created_by_role:"CODER_AI",source_coder_tasks:{coder_tasks_id:"TASKS-001",coder_tasks_record_path:"governance/context/coder_tasks/TASKS-001.json",coder_work_plan_id:"WORKPLAN-001",tasking_id:"TASKING-001",code_flow_id:flowId,plan_id:"PLAN-001",specification_id:"SPEC-001",intake_id:"INTAKE-001",handoff_id:"PM-HANDOFF-001",share_id:"SHARE-001",science_flow_id:"SCIENCE-001",share_packet_hash:"sharehash",submitted_share_payload_hash:"submitted-share",handoff_payload_hash:"pm-handoff-hash",intake_payload_hash:"intake-hash",specification_payload_hash:"spec-hash",plan_payload_hash:"plan-hash",tasking_payload_hash:"tasking-hash",coder_work_plan_payload_hash:"workplan-hash",coder_tasks_payload_hash:"tasks-hash",evidence_level:"SUPPORTED_DIAGNOSTIC",uncertainty:"diagnostic only",source_artifacts:["SRC-001"],resolved_source_artifacts:[{artifact_id:"SRC-001",artifact_type:"audit_report",title:"Audit",role:"SCIENCE_AUDITOR_AI",created_at:"2026-01-01T00:00:00.000Z",source_path:"source.md",source_sha:"sha-source"}],allowed_claims:["diagnostic proposal only"],forbidden_claims:["no certification","no production readiness"]},output_artifacts:{implementation_bundle:art},submitted_payload_hash:"impl-payload-hash",implementation_bundle_record_path:rec,generated_coder_implementation_bundle_context_path:"governance/context/generated_coder_implementation_bundle_context.json",required_status_labels:labels}));
files.set(`governance/flows/${flowId}/flow_manifest.json`,JSON.stringify({schema_version:"flow_manifest.v0.3",official_artifact:true,project:"ArqonZero",flow_id:flowId,name:"code-flow",type:"code_flow",title:"Code Flow",summary:"",status:"active",current_gate:"DRAFT",created_at:"2026-01-01T00:00:00.000Z",created_by_role:"PM_AI",updated_at:"2026-01-01T00:00:00.000Z",updated_by_role:"PM_AI",required_status_labels:labels,artifacts:[art],history:[]}));
files.set("governance/flows/flow_index.json",JSON.stringify({schema_version:"flow_index.v0.3",project:"ArqonZero",updated_at:"2026-01-01T00:00:00.000Z",flows:[{flow_id:flowId,name:"code-flow",type:"code_flow",title:"Code Flow",status:"active",current_gate:"DRAFT",created_at:"2026-01-01T00:00:00.000Z",updated_at:"2026-01-01T00:00:00.000Z",source_path:`governance/flows/${flowId}/flow_manifest.json`}]})); return {flowId,implId,rec}; }
async function main(){ const {flowId,implId,rec}=seed(); const noAuth=await post("/v1/coder/handoff","NONE",{}); assert(noAuth.status===401,"no-auth must be denied"); for(const role of ["PM","HELPER","AUDITOR"] as const){ const d=await post("/v1/coder/handoff",role,{implementation_bundle_id:implId,idempotency_key:"handoff-denied-0001",handoff_title:"Denied",handoff_body:"proposal only"}); assert(d.status===403,`${role} must be denied`); }
const raw=await post(`/v1/flows/${flowId}/artifacts`,"CODER",{artifact_type:"coder_handoff",title:"Raw",body:"raw generic coder_handoff must be blocked"}); assert(raw.status===403 && raw.body.error.code==="FLOW_ARTIFACT_ROUTE_REQUIRED","raw generic coder_handoff must be route-only");
const body={implementation_bundle_id:implId,idempotency_key:"handoff-ok-0001",handoff_title:"Coder Handoff OK",handoff_body:"Coder handoff package for later review only. Execution remains gated pending later stages."}; const ok=await post("/v1/coder/handoff","CODER",body); assert(ok.status===201,`handoff should succeed ${ok.status} ${JSON.stringify(ok.body)}`); assert(ok.body.coder_handoff.output_artifacts.coder_handoff.artifact_type==="coder_handoff","artifact missing"); assert(!writes.some(p=>p.includes("execution_report")||p.includes("command_log")||p.includes("helper_log")),"must not write execution artifacts");
const replay=await post("/v1/coder/handoff","CODER",body); assert(replay.status===200 && replay.body.idempotent_replay===true,"replay must be idempotent"); const conflict=await post("/v1/coder/handoff","CODER",{...body,handoff_body:"changed"}); assert(conflict.status===409 && conflict.body.error.code==="CODER_HANDOFF_IDEMPOTENCY_CONFLICT","conflict expected");
const mismatch=await post("/v1/coder/handoff","CODER",{implementation_bundle_id:implId,implementation_bundle_record_path:"governance/context/coder_implementation_bundle/WRONG.json",idempotency_key:"handoff-mismatch-0001",handoff_title:"Mismatch",handoff_body:"proposal only"}); assert(mismatch.status===409 && mismatch.body.error.code==="CODER_HANDOFF_IMPLEMENTATION_BUNDLE_CONTEXT_MISMATCH","mismatch expected");
const promo=await post("/v1/coder/handoff","CODER",{implementation_bundle_id:implId,idempotency_key:"handoff-promo-0001",handoff_title:"Promo",handoff_body:"approved for release"}); assert(promo.status===409 && promo.body.error.code==="CODER_HANDOFF_FORBIDDEN_CLAIM_INCLUDED","promo denied"); const exec=await post("/v1/coder/handoff","CODER",{implementation_bundle_id:implId,idempotency_key:"handoff-exec-0001",handoff_title:"Exec",handoff_body:"Helper may execute this now"}); assert(exec.status===409 && exec.body.error.code==="CODER_HANDOFF_EXECUTION_AUTHORITY_FORBIDDEN","exec denied");
const r=JSON.parse(files.get(rec)||"{}"); r.output_artifacts.implementation_bundle.source_sha="wrong"; files.set(rec,JSON.stringify(r)); const sha=await post("/v1/coder/handoff","CODER",{implementation_bundle_id:implId,idempotency_key:"handoff-sha-0001",handoff_title:"SHA",handoff_body:"proposal only"}); assert(sha.status===409 && sha.body.error.code==="CODER_HANDOFF_IMPLEMENTATION_BUNDLE_ARTIFACT_SHA_MISMATCH","sha mismatch expected"); console.log(JSON.stringify({ok:true,raw_status:raw.status,success_status:ok.status,replay_status:replay.status,conflict_status:conflict.status,mismatch_status:mismatch.status,promotion_status:promo.status,execution_status:exec.status,sha_status:sha.status,wrote_execution_artifacts:writes.some(p=>p.includes("execution_report")||p.includes("command_log")||p.includes("helper_log"))},null,2)); }
main().catch(e=>{console.error(e);process.exitCode=1;});
