#!/usr/bin/env python3
from pathlib import Path
import json, sys
R=Path.cwd()
need=["worker/src/coder_handoff.ts","worker/src/index.ts","worker/src/flows.ts","worker/test_support/code_monkeys_coder_handoff_offline_smoke.ts","worker/test_support/code_monkeys_coder_handoff_policy_unit.ts","docs/04_flows_and_spec_kit/CODE_MONKEYS_CODER_HANDOFF_001.md"]
missing=[p for p in need if not (R/p).exists()]
if missing: print(json.dumps({"ok":False,"result":"FAIL","missing":missing},indent=2)); sys.exit(1)
handler=(R/"worker/src/coder_handoff.ts").read_text(); index=(R/"worker/src/index.ts").read_text(); flows=(R/"worker/src/flows.ts").read_text(); smoke=(R/"worker/test_support/code_monkeys_coder_handoff_offline_smoke.ts").read_text(); doc=(R/"docs/04_flows_and_spec_kit/CODE_MONKEYS_CODER_HANDOFF_001.md").read_text()
checks=[("route mounted","/v1/coder/handoff" in index and "handleCoderHandoffRequest" in index),("coder only",'role !== "CODER_AI"' in handler and "CODER_HANDOFF_ROLE_FORBIDDEN" in handler),("context consumed","generated_coder_implementation_bundle_context.json" in handler),("schema checked","coder_implementation_bundle_context.v0.1" in handler),("route-only",'"coder_handoff"' in flows and "FLOW_ARTIFACT_ROUTE_REQUIRED" in flows),("idempotency","CODER_HANDOFF_IDEMPOTENCY_CONFLICT" in handler),("promotion guard","CODER_HANDOFF_FORBIDDEN_CLAIM_INCLUDED" in handler),("execution guard","CODER_HANDOFF_EXECUTION_AUTHORITY_FORBIDDEN" in handler),("title guard wired","validateText(title)" in handler),("sha guard","CODER_HANDOFF_IMPLEMENTATION_BUNDLE_ARTIFACT_SHA_MISMATCH" in handler),("offline raw route-only","raw generic coder_handoff must be route-only" in smoke),("offline no execution artifacts","wrote_execution_artifacts" in smoke),("offline promotion title check","promo title denied" in smoke and "approved for release" in smoke),("offline execution title check","exec title denied" in smoke and "helper may execute" in smoke),("labels",all(x in doc for x in ["REQUIRES_HUMAN_REVIEW","development diagnostic only","NOT SEALED-TEST CERTIFIED","not promotable"]))]
bad=[n for n,o in checks if not o]
print(json.dumps({"ok":not bad,"result":"PASS" if not bad else "FAIL","failures":bad,"checks":[n for n,_ in checks]},indent=2)); sys.exit(1 if bad else 0)
